portfolio/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from profile.views import index as index_profile
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^profile/', include('profile.urls')),
    re_path(r'^resume/', include('resume.urls')),
    re_path(r'^portfolio/', include('portfolio.urls')),
    re_path(r'^login', login_view, name='login'),
    re_path(r'^logout', logout_view, name='logout'), 
    re_path(r'^$', index_profile, name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profile/urls.py
from django.urls import re_path
from .views import index, message_post, message_table
#url for app

app_name = 'profile'

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^add_message', message_post, name='add_message'),
    re_path(r'^result_table', message_table, name='result_table'), 
]

resume/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

portfolio/models.py
from django.db import models

# Create your models here.

profile/models.py
from django.db import models

# Create your models here.

from django.db import models

class Message(models.Model):
	name = models.CharField(max_length=27)
	email = models.EmailField()
	message = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

	def __str__ (self):
		return self.message

resume/models.py
from django.db import models

# Create your models here.

profile/forms.py
from django import forms

class Message_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
		'invalid': 'Isi input dengan email',
	}
	
	attrs = {
		'class': 'form-control'
	}

	name = forms.CharField(label='Nama', required=False, max_length=27,empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
	email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
	message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

portfolio/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	response = {

	}
	return render(request, 'portfolio.html', response)

praktikum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

def login_view(request):
    response = {}
    # user = None
    if request.method == "POST":
        user_login = request.POST['username']
        pass_login = request.POST['password']

        user = authenticate(request, username=user_login, password=pass_login)
        print(user)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('login')
    html = 'login.html'
    return render(request, html, response)

def logout_view(request):
    response = {}

    if request.method == "POST":
        print(request.POST)
        if request.POST["logout"] == "Submit Query":
            logout(request)
        return HttpResponseRedirect('/')

    return render(request, 'logout.html', response)


def inici(request):
    zones = Zona.objects.all()
    return render_to_response('layout/base.html', dict(zones=zones),
        context_instance = RequestContext(request))

profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from .forms import Message_Form
from .models import Message
from datetime import datetime, date


mhs_name = 'Rully Fildansyah'  
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998, 7, 11)  
departement = 'Teknik Informatika' 										
city = 'Sukabumi' 
phone = '+62 898 6431 126'
email = 'rullfhiel@gmail.com'														
interest = 'Web developer, IOT & Pythonista' 					
instagram = 'https://www.instagram.com/rvllfil/'						
github = 'https://github.com/rvllfil'									
linkedin = 'https://www.linkedin.com/in/rully-fildansyah-7a85b0168/'  	
twitter = 'https://twitter.com//rvllfil'								

# Create your views here.

def index(request):
    response = {
        'name': mhs_name,
        'age': calculate_age(birth_date.year),
        'birth_date': birth_date,
        'departement': departement,
        'city': city,
        'phone': phone,
        'email': email,
        'interest': interest,
        'instagram': instagram,
        'github': github,
        'linkedin': linkedin,
        'twitter': twitter
    }
    response['message_form'] = Message_Form
    return render(request, 'index_profile.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'], message=response['message'])
        message.save()
        html ='form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')


def message_table(request):
    response = {}
    message = Message.objects.all()
    response['message'] = message
    html = 'table.html'
    return render(request, html , response)

resume/views.py
from django.shortcuts import render

# Create your views here.
	
mhs_name = 'Rully Fildansyah' 

def index(request):
	response = {
	'name': mhs_name,

	}
	return render(request, 'resume.html', response)

portfolio/templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<title>{{ name }}</title>
	{% include "snippets/styles.html" %}
	<link rel="stylesheet" href="{% static 'resume/css/styles.css' %}">
</head>

<body>

	{% include "snippets/navbar.html" %}

	<section class="mt-5">
		<div class="container text-center">
			<br><br><br><br><br><br>
			<h1>Mohon maaf portfolio belum tersedia untuk saat ini</h1>
		</div>
	</section>


		<!-- footer -->
	{% include "snippets/footer.html" %}
	
	
	<!-- script js bootstrap -->
	{% include "snippets/scripts.html" %}

</body>

</html>

profile/templates/index_profile.html
{% extends "layout/base.html" %}
{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static "profile/css/styles.css" %}">
{% endblock styles %}

{% block header %}
	<h1 class="display-4">Hallo {{ user }}</h1>
{% endblock header %}

{% block content %}	
<!-- About Me -->
<div id="About">
	<div class="container">
		<div class="row">
			<div class="col">
				<div id="AboutData">
					<div class="card bg-white">
						<div class="card-title my-5">
							<div class="media">
								<img src="{% static "img/my_photo.png" %}" width="250" height="250" class="img-fluid rounded-top mx-5 d-none d-lg-block" alt="">
								<div class="media-body">
									<h3 class="display-4 ml-5"> I'm {{ name }}</h3>
									<p class="text-muted ml-5" >{{ interest }}</p>
									<div class="container">
										<table class="table table-responsive ml-4">
											<tr>
												<td >Age</td>
												<td>:</td>
												<td>{{ age }} Years Old</td>
											</tr>
											<tr>
												<td>Email</td>
												<td>:</td>
												<td>{{ email }}</td>
											</tr>	
											<tr>
												<td>Phone</td>
												<td>:</td>
												<td>{{ phone }}</td>
											</tr>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="card-footer bg-light d-none d-lg-block">
							<a href="https://www.instagram.com/rvllfil/"><i class="fab fa-instagram fa-2x mx-3"></i></a>
							<a href="https://twitter.com/rvllfil/"><i class="fab fa-twitter fa-2x mx-3"></i></a>
							<a href="https://github.com/rvllfil/"><i class="fab fa-github fa-2x mx-3"></i></a>
							<a href="https://gitlab.com/rvllfil"><i class="fab fa-gitlab fa-2x mx-3"></i></a>
							<a href="https://www.linkedin.com/in/rully-fildansyah-7a85b0168/"><i class="fab fa-linkedin fa-2x mx-3"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<section name="contact" class="contact container-fluid py-5">
	<div class="container">
		<div class="d-flex flex-column align-items-center">
			<h1>Contact Me</h1>
		</div>
		<div class="row">
			<div class="col-md-6 col-sm-12 d-flex justify-content-center align-items-center py-3">
				<i class="fas fa-envelope-open-text"></i>
			</div>
			<div class="col-md-6 col-sm-12 px-5 py-5">
				<form id="form" method="POST" action="{% url 'profile:add_message' %}">
					{% csrf_token %}
					{{ message_form }}
					<br>
					<button type="submit" class="btn btn-primary btn-block">Submit</button>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock content %}	
	

resume/templates/resume.html
{% extends "layout/base.html" %}
{% load static %}

{% block title %}
{{ name }} - Resume
{% endblock title %}

{% block header %}
   <h1 class="display-4">My Resume</h1>
{% endblock header %}


{% block styles %}
<link rel="stylesheet" href="{% static 'resume/css/styles.css' %}">
{% endblock styles %}

{% block content %}
	
<!-- education background -->
<section id="education">
	<div class="container">
		<div class="row">
			<div class="col text-center">
				<h1>Educational Background</h1>
			</div>
		</div>
		<div class="row justify-content-center mt-5">
			<div class="col-md">
				<div class="card mb-5" style="width: 14rem;">
					<div class="card-body">
				   		<h5 class="card-title">Elementary School</h5>
				    	<h6 class="card-subtitle mb-2 text-muted">2005 - 2011</h6>
				    	<p class="card-text">SDN Bojongkawung</p>
				  </div>
				</div>
			</div>
			<div class="col-md">
				<div class="card mb-5" style="width: 14rem;">
				  	<div class="card-body">
				   		<h5 class="card-title">Junior High School</h5>
				    	<h6 class="card-subtitle mb-2 text-muted">2011 - 2014</h6>
				    	<p class="card-text">SMPN 3 Cibadak</p>
				  	</div>
				</div>
			</div>
			<div class="col-md">
				<div class="card mb-5" style="width: 14rem;">
				  	<div class="card-body">
				   		<h5 class="card-title">High School</h5>
				    	<h6 class="card-subtitle mb-2 text-muted">2014 - 2017</h6>
				    	<p class="card-text">SMKN 1 Kota Sukabumi</p>
				  	</div>
				</div>
			</div>
			<div class="col-md">
				<div class="card mb-5" style="width: 14rem;">
				  	<div class="card-body">
				   		<h5 class="card-title">University</h5>
				    	<h6 class="card-subtitle mb-2 text-muted">2017 - now</h6>
				    	<p class="card-text">Nusa Putra University</p>
				  	</div>
				</div>
			</div>
		</div>
	</div>
</section>


<!-- my experience -->
<section id="experience">
	<div class="container">
		<div class="row">
			<div class="col text-center mt-5 mb-3">
				<h1>My Experience</h1>
			</div>
		</div>
		<div class="row mt-4 mb-4">
			<div class="col-md-4">
				<div class="card mb-4" style="width: 18rem;">
					<img src="{% static "resume/img/pic1.jpg" %}" class="card-img-top" alt="pic1">
				  	<div class="card-body">
				    	<h5 class="card-title">Diksar Resimen Mahasiswa</h5>
				    	<p class="card-text">Mengikuti Diksar Resimen Mahasiswa Mahawarman di secata TNI AD Pangalengan, Bandung Selatan.<br><br>tahun 2018</p>
				  	</div>
				</div>
			</div>
			<div class="col-md-4 mb-4">
				<div class="card mb-4" style="width: 18rem;">
					<img src="{% static "resume/img/pic2.jpg" %}" class="card-img-top" alt="pic2">
				  	<div class="card-body">
				    	<h5 class="card-title">PKL</h5>
				    	<p class="card-text">PKL sebagai peng-upload code pada chip ic di PT.SGP Indonesia. <br><br>tahun 2015</p>
				  	</div>
				</div>
			</div>
			<div class="col-md-4 mb-4">
				<div class="card mb-4" style="width: 18rem;">
					<img src="{% static "resume/img/pic3.png" %}" class="card-img-top" alt="pic3">
				  	<div class="card-body">
				    	<h5 class="card-title">Peserta Digitalent</h5>
				    	<p class="card-text">Menjadi peserta Digitalent Scholarship dari Kemenkominfo di bidang Programming Essential in Python. <br><br>tahun 2019</p>
				  	</div>
				</div>
			</div>
		</div>
	</div>
</section>


<!-- My Skills -->
<section id="skills">
	<div class="container">
		<div class="row">
			<div class="col text-center mt-4">
				<h1>My Skills</h1>
			</div>
		</div>
		<div class="row mt-4 mb-4">
			<div class="col-md">
				<div class="card mb-4" style="width: 18rem;">
					<img src="{% static "resume/img/html.svg" %}" class="card-img-top" alt="html">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
									75%
								</div>
						</div>
				  	</div>
				</div>
			</div>
			<div class="col-md mb-4">
				<div class="card" style="width: 18rem;">
					<img src="{% static "resume/img/css.svg" %}" class="card-img-top" alt="css">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">
									60%
								</div>
						</div>
				  	</div>
				</div>
			</div>
			<div class="col-md mb-4">
				<div class="card" style="width: 18rem;">
					<img src="{% static "resume/img/js.svg" %}" class="card-img-top" alt="js">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
									50%
								</div>
						</div>
				  	</div>
				</div>
			</div>
			<div class="col-md mb-4">
				<div class="card" style="width: 18rem;">
					<img src="{% static "resume/img/python.svg" %}" class="card-img-top" alt="python">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100">
									80%
								</div>
						</div>
				  	</div>
				</div>
			</div>
			<div class="col-md mb-4">
				<div class="card" style="width: 18rem;">
					<img src="{% static "resume/img/django.svg" %}" class="card-img-top" alt="django">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
									50%
								</div>
						</div>
				  	</div>
				</div>
			</div>
			<div class="col-md mb-4">
				<div class="card" style="width: 18rem;">
					<img src="{% static "resume/img/arduino.svg" %}" class="card-img-top" alt="arduino">
				  	<div class="card-body">
				    	<div class="progress">
								<div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100">
									85%
								</div>
						</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

templates/form_result.html
{% extends "layout/base.html" %}

{% block styles %}
<style>
body {
	background: rgba(11, 12, 16, 1);
}
.message {
	margin-top: 50px;
}
</style>
{% endblock styles %}

{% block title %} Pesan dari {{ name }} {% endblock %}

{% block header %}
<div class="message">
	<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-
	{{name}}
	by {{ email }}
	</textarea>
</div>
{% endblock header %}

{% block content %}

{% endblock %}

templates/layout/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head lang="en">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="mysite">
	<meta name="author" content="{{ name }}">

	<title>{% block title %}{{ name }}{% endblock title %}</title>
	<link href="https://fonts.googleapis.com/css?family=Luckiest+Guy|Nunito|Permanent+Marker&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/all.css' %}">
	<link rel="stylesheet" href="{% static "css/styles.css" %}">
	<link rel="stylesheet" href="{% static "css/chatbox.css" %}">
	{% block styles %}{% endblock styles %}
</head>

<body>
	<!-- navbar -->
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
	    <div class="container">    
	        <a class="navbar-brand" href="/"><h3>UPIL</h3></a>
	        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	          <span class="navbar-toggler-icon"></span>
	        </button>

	        <div class="collapse navbar-collapse" id="navbarSupportedContent">
	            <ul class="navbar-nav ml-auto">
	                <li class="nav-item">
	                <a class="nav-link" href="/">Profile</a>
	                </li>
	                <li class="nav-item">
	                <a class="nav-link" href="/resume">Resume</a>
	                </li>
	                </li>
	                <li class="nav-item">
	                <a class="nav-link" href="/portfolio">Portfolio</a>
	                </li>
	                {% if user.is_authenticated %}     
	                    <li class="nav-item">
	                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
	                    </li>
	                    {% if user.is_superuser %}                   
	                        <li class="nav-item">
	                        <a class="nav-link" href="{% url 'profile:result_table' %} ">See Messages</a>
	                        </li>
	                    {% endif %}  
	                {% else %}
	                    <li class="nav-item">
	                    <a class="nav-link" href="{% url 'login' %}">Login</a>
	                    </li>
	                {% endif %}
	        </div>
	    </div>
	</nav>


	<!-- header -->	
	<div class="jumbotron jumbotron-fluid">
  		<div class="container">
  			{% block header %}
    		<h1 class="display-4">Welcome to My Portfolio</h1>
  			{% endblock header %}
  		</div>
	</div>	

	<!-- content -->
	{% block content %}
		
	{% endblock content %}

	<!-- chatbox -->
	{% block chatbox %}
		{% if user.is_authenticated %}
			{% include "partials/chatbox.html" %}
		{% else %}

		{% endif %}

	{% endblock chatbox %}
	

	<!-- footer -->
	{% include "partials/footer.html" %}

	<!-- scripts js bootstrap -->
	<script src="{% static 'vendor/jquery/jquery-3.3.1.slim.min.js' %}" type="text/javascript" ></script>
	<script src="{% static 'vendor/popper/popper.min.js' %}" type="text/javascript" ></script>
	<script src="{% static 'vendor/bootstrap/bootstrap.js' %}" type="text/javascript" ></script>
	<script src="{% static 'js/chatbox.js' %}" type="text/javascript" ></script>	
	{% block script %}{% endblock script %}

</body>
</html>

templates/login.html
{% extends "layout/base.html" %}
{% load static %}

{% block styles %}
<style>
	.group {
		margin-right: 400px;
		margin-left: 400px;	
	}

	body {
		background: #C5C6C7;
	}

</style>
	
{% endblock styles %}

{% block chatbox %}
	
{% endblock chatbox %}

{% block header %}
	<h1 class="display-4">Login</h1>
{% endblock header %}

{% block content %}
	<div class="container">
		<div class="form-group group text-center">
			<form method="POST">
				{% csrf_token %}
				<input type="text" name="username" id="username" placeholder="Username" class="form-control">
				<br>
				<input type="password" name="password" id="password" placeholder="Password" class="form-control">
				<br>
				<button type="submit" class="btn btn-primary btn-block">Login</button>	
			</form> 
		</div>
	</div>
{% endblock content %}

templates/logout.html
 <!DOCTYPE html>
 <html>
 <head>
 	<title>Logout</title>
 </head>
 <body>

 	<h1>Logout</h1>
 	<p>Apakah anda yakin akan logout?</p>

 	<form method="POST">
 		{% csrf_token %}
 		<input type="submit" name="logout" class="form-control">
 	</form>
 
 </body>
 </html>

templates/partials/chatbox.html
<!-- ChatBox Section -->
<section name="Chatbox">
	<div class="wrapper">
		<div class="chat-box">
			<div class="chat-head">
				<h2>Chat</h2>
				<img src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_down-16.png" title="Expand Arrow" width="16">
			</div>
			<div class="chat-body">
				<div class="msg-insert"></div>
				<div class="chat-text">
					<textarea placeholder="Press Enter"></textarea>
				</div>
			</div>
		</div>
	</div>
</section>

templates/partials/footer.html
	<div class="container-fluid" id="footer">
		<div class="row">
			<div class="col">
				<div class="container">
					<p class="text-white pt-2 text-center">Made with <i class="fas fa-heart"></i> using <i class="fab fa-python"></i> by upil <br><i class="far fa-copyright">Copyright</i> 2019</p>
				</div>
			</div>
		</div>
	</div>

templates/partials/navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
    <div class="container">    
        <a class="navbar-brand" href="/"><h3>UPIL</h3></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                <a class="nav-link" href="/">Profile</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/resume">Resume</a>
                </li>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="/portfolio">Portfolio</a>
                </li>
                {% if user.is_authenticated %}     
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% if user.is_superuser %}  
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>                    
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:result_table' %} ">See Messages</a>
                        </li>
                    {% endif %}  
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
        </div>
    </div>
</nav>

templates/table.html
{% extends "layout/base.html" %}
{% block title %} Kumpulan Pesan {% endblock %}

{% block styles %}
<style>
body {
	background: #1F2833;
}
#content {
	background: #C5C6C7 !important;
}
</style>
{% endblock styles %}

{% block header %}
<h1 class="display-4">Messages</h1>
{% endblock header %}

{% block content %}
<div class="content py-5">
	<div class="container" id="content">
	<table class="table">
		<thead>
			<th>Nama</th>
			<th>Email</th>
			<th>Pesan</th>
			<th>Dibuat Pada</th>
		</thead>	
		<tbody>
			<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
			{% for i in message %}
			{% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
			<tr class="table-warning"> {% else %} <tr class="success">
				{% endif %}
				<td> {{i.name}} </td>
				<td> {{i.email}} </td>
				<td> {{i.message}} </td>
				<td> {{i.created_date.time}} </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	</div>
</div>
{% endblock %}